### PR TITLE
Fix Localized Entry Serializing

### LINKED ISSUE #29: Locales option
How can you import content with different locales?

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #29

### CODE REVIEW

File: spec/spec_helper.rb [hunk 1]
```diff
@@ -33,12 +38,24 @@ def initialize(id = 'content_type')
...
+  def initialize(id = '', content_type = ContentTypeDouble.new, fields = {}, locales = false)
     @id = id
     @content_type = content_type
-    @fields = fields
+    @fields = {}
+    if locales
+      @fields = fields
+    else
+      fields.each do |k, v|
+        @fields['en-US'] ||= {}
```
Comment (mariobodemann) [inline spec/spec_helper.rb]: This can probably done outside of the `.each` loop, since it is not dependant on k,v, right?

File: spec/spec_helper.rb [hunk 2]
```diff
@@ -33,12 +38,24 @@ def initialize(id = 'content_type')
...
 class EntryDouble < Contentful::DynamicEntry
-  attr_reader :id, :content_type, :fields
+  attr_reader :id, :content_type
 
-  def initialize(id = '', content_type = ContentTypeDouble.new, fields = {})
+  def initialize(id = '', content_type = ContentTypeDouble.new, fields = {}, locales = false)
     @id = id
     @content_type = content_type
-    @fields = fields
+    @fields = {}
```
Comment (mariobodemann) [inline spec/spec_helper.rb]: That feels like a double assignement, since the if following it will always overwrite it, right?

Comment (dlitvakb) [inline spec/spec_helper.rb]: No, because the @fields needs to exist previously for the case in which `locales = false`, which is actually all but 1 test.

Comment (mariobodemann) [inline spec/spec_helper.rb]: Ah, gotcha!
